version: '3.8'

services:
  web:
    build: ./Backend/Server
    command: flask run -h 0.0.0.0
    volumes:
      - ./Backend/Server/:/usr/src/app/Backend/Server/
    ports:
      - 5000:5000
    env_file:
      - ./Backend/Server/.flaskenv