version: '3.8'

services:
  web:
    build: ./
    command: flask run -h 0.0.0.0
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - .flaskenv


  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .flaskenv

volumes:
  postgres_data:
    