version: '3.8'

services:
  web:
    build:
      dockerfile: Dockerfile.prod 
    command: gunicorn --bind 0.0.0.0:5000 --workers=2 'app:app'
    expose:
      - 5000
    env_file:
      - .flaskenv
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.flaskenv

  nginx:
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data_prod: